### ISSUE TITLE
cz.msebera.android.httpclient.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by wangjunhui** [loopj/android-async-http#1001]
```
   cz.msebera.android.httpclient.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
       at cz.msebera.android.httpclient.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:412)
       at cz.msebera.android.httpclient.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:298)
       at cz.msebera.android.httpclient.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:238)
       at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
       at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:879)
       at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
       at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
       at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by nezen** [comment]
I have the same problem when I try to upload a few files to an embedded device sequentially. I wonder it's a confirmed problem or not?

**Comment by lcj0304** [comment]
i have the same problem!

**Comment by wangjunhui** [comment]
hi，can you fix this problem ? my project was delayed . thank you!!!

**Comment by Racer23** [comment]
how deal it

**Comment by mnomansadiq** [comment]
Still not fix ?
