### ISSUE TITLE
Custom CA Sample not working

### ISSUE THREAD

**Issue by rferbesa** [loopj/android-async-http#1008]
Hello!
I've been using this library with success for a long time. Now I have to connect to a SSL server with its custom certificate. I've tried to follow all steps in my app and it's not working so I've tried to run the sample, with no modifications, and it's not working too.
This is what I've done:
- I've downloaded the loopj samples project.
- I've made a clean, a rebuild and I've run the project just as it is in my Samsung Galaxy S5 and in my Sony Xperia.
- Once the app is launched in my mobile I select CustomCASample cell.
- I click on Run and the log shows me this error in both devices:

10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Chain includes 3 certificates.
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Server Certificate Details:
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ ---------------------------
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ IssuerDN: CN=RapidSSL SHA256 CA - G3, O=GeoTrust Inc., C=US
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ SubjectDN: CN=*.fineswap.com, OU=Domain Control Validated - RapidSSL(R), OU=See www.rapidssl.com/resources/cps (c)14, OU=GT19090574
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Serial Number: 78622
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Version: 3
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Not before: Thu Dec 18 18:09:39 CET 2014
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ Not after: Mon Mar 21 08:38:30 CET 2016
10-23 16:21:04.199  16178-16314/com.loopj.android.http.sample I/SecureSocketFactory﹕ ---------------------------
10-23 16:21:04.209  16178-16314/com.loopj.android.http.sample E/SecureSocketFactory﹕ Certificate error
    java.security.SignatureException: signature did not verify
            at com.android.org.conscrypt.OpenSSLX509Certificate.verifyInternal(OpenSSLX509Certificate.java:358)
            at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:371)
            at com.loopj.android.http.sample.util.SecureSocketFactory$1.checkServerTrusted(SecureSocketFactory.java:135)
            at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:613)
            at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
            at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
            at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
            at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
            at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
            at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
            at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
            at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
            at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
            at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
            at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
            at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

Both my Sony Xperia and my Samsung Galaxy S5 have the correct date and time just in case this is important.

So, Am I missing something? Should I do anything else to avoid this error?

Thank you very much and kind regards!

**Comment by fineswap** [comment]
@rferbesa 

The sample example isn't working because the SSL server that used to serve the custom certificate is  down. Since Fineswap is launching soon, we decided to switch to a non-custom SSL, so that's why the sample isn't working.

The server-side work, however, is easy enough to do on your own. The large portion of work is done on the client-side, which is shown in the sample Java code.

**Comment by rferbesa** [comment]
Ok! 
What I've done now is to take the sample and change TEST_SERVER, STORE_ALIAS, STORE_PASS and bks file to those I have to use, and the error is exactly the same again. As far as I know the iOS version of the Android app I'm developing is working properly with that certificate and server, so I guess there is no problem in the server side.
I've looked into SSLLabs.com test but I don't know what to check in that huge report.

**Comment by DonTharaka** [comment]
this solved my issue : http://stackoverflow.com/questions/11573108/self-signed-certificate-and-loopj-for-android
