### ISSUE TITLE
getSSLSocketMiddleware resource

### ISSUE THREAD

**Issue by msysmilu** [loopj/android-async-http#1010]
In `Ion.class` 2.1.6, line 179, `this.httpClient.getSSLSocketMiddleware()` errors and it seems the correct call would be: `this.getHttpClient().getSSLSocketMiddleware()`

**Comment by msysmilu** [comment]
Though I might be wrong as I have downloaded the class again with Android Studio and the line layout is different.

**Comment by msysmilu** [comment]
this is my trace:
`
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime: FATAL EXCEPTION: Timer-0
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime: Process: iibm.mose5, PID: 11056
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getSSLSocketMiddleware()Lcom/koushikdutta/async/http/spdy/SpdyMiddleware; in class Lcom/koushikdutta/async/http/AsyncHttpClient; or its super classes (declaration of 'com.koushikdutta.async.http.AsyncHttpClient' appears in /data/app/iibm.mose5-1/base.apk)
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime:     at com.koushikdutta.ion.Ion.<init>(Ion.java:156)
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime:     at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime:     at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
10-26 16:08:51.466 11056-11139/iibm.mose5 E/AndroidRuntime:     at com.koushikdutta.ion.Ion.with(Ion.java:72)
`
