### ISSUE TITLE
App Crashing on Attempt to get length of null array

### ISSUE THREAD

**Issue by faizandedia** [loopj/android-async-http#1087]
Application is crashing and throws below exception. I am using lollipop

 java.lang.NullPointerException: Attempt to get length of null array
  at java.lang.String.<init>(String.java:119)
  at ae.gov.dsg.network.AbstractHttpClient$5.onFailure(AbstractHttpClient.java:505)
  at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359)
  at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:6872)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by faizandedia** [comment]
Issue was related to something else.
