### ISSUE TITLE
IllegalStateException in AsyncHttpResponseHandler

### ISSUE THREAD

**Issue by mdalikazi** [loopj/android-async-http#1089]
Cant even login to my app after updating to android-async-http 1.4.9 and using the new httpclient library 4.4.1.1. Hope its an easy fix and is coming soon.

```
java.lang.IllegalStateException: Handler (com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler) {1b177bb9} sending message to a Handler on a dead thread
              at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
              at android.os.Handler.enqueueMessage(Handler.java:631)
              at android.os.Handler.sendMessageAtTime(Handler.java:600)
              at android.os.Handler.sendMessageDelayed(Handler.java:570)
              at android.os.Handler.sendMessage(Handler.java:507)
              at com.loopj.android.http.AsyncHttpResponseHandler.sendMessage(AsyncHttpResponseHandler.java:404)
              at com.loopj.android.http.AsyncHttpResponseHandler.sendFinishMessage(AsyncHttpResponseHandler.java:329)
              at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:119)
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
              at java.lang.Thread.run(Thread.java:818)
```
This is the method causing the error:
```
protected void sendMessage(Message msg) {
        if (getUseSynchronousMode() || handler == null) {
            handleMessage(msg);
        } else if (!Thread.currentThread().isInterrupted()) { 
            // do not send messages if request has been cancelled
            Utils.asserts(handler != null, "handler should not be null!");
            handler.sendMessage(msg);
        }
    }
```

My gradle:
```
...
android {
    compileSdkVersion 22
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com...."
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 20
        versionName "1.0.14"
        multiDexEnabled true
    }
compile 'com.loopj.android:android-async-http:1.4.9'
compile group: 'cz.msebera.android' , name: 'httpclient' , version: '4.4.1.1'
...
```
Thanks for your contribution.

**Comment by mdalikazi** [comment]
I had to set 
```
@Override
    public void setUsePoolThread(boolean pool) {
        super.setUsePoolThread(true);
    }
```
when declaring the AsyncHttpResponseHandler.
