### ISSUE TITLE
AsyncHttpResponseHandler﹕ User-space exception Problem

### ISSUE THREAD

**Issue by CnkGn** [loopj/android-async-http#1116]
Hello everyone, I encountered such a problem. I am use loopj in my project.

`02-26 15:57:38.247: E/AsyncHttpRH(2661): User-space exception detected!
02-26 15:57:38.247: E/AsyncHttpRH(2661): java.lang.NullPointerException
02-26 15:57:38.247: E/AsyncHttpRH(2661): 	at com.example.ProgramActivity$1.onSuccess(ProgramActivity.java:125)
`
How can i fix this problem?

**Comment by gaobq** [comment]
show your samplecode

**Comment by CnkGn** [comment]
```
XYXAPI.get(getApplicationContext(), url, new AsyncHttpResponseHandler() {
			@Override
			public void onStart() {
				
			}

			@Override
			public void onSuccess(int statusCode, Header[] headers,
					byte[] response) {
				String responseStr = new String(response);

				try {
						//Json parse
					}

				} catch (JSONException e) {
					e.printStackTrace();
				} finally {

					//set adapter
				}

			}

			@Override
			public void onFailure(int statusCode, Header[] headers,
					byte[] errorResponse, Throwable e) {

				if (errorResponse != null) {
					Log.i("info", new String(errorResponse));
				} else {
					Log.e("info", "something got very very wrong");
				}
			}

			@Override
			public void onRetry(int retryNo) {
				Log.e("info", "Retry #" + retryNo);
			}
		});
```

**Comment by CnkGn** [comment]
@gaobq 
```
public class XYZAPI {
	private static AsyncHttpClient client = new AsyncHttpClient();
        public static void get(Context context, String url,
			AsyncHttpResponseHandler responseHandler) {
		client.get(url, responseHandler);	
	}
```

**Comment by gaobq** [comment]
which  asynchttp version you used?
you can see the GetSample.java in folder sample
it have 5 params
context,url,headers,entity,responsehandler
and entity can be null

**Comment by gaobq** [comment]
@CnkGn 
could you show me the real code about :E/AsyncHttpRH(2661): at com.example.ProgramActivity$1.onSuccess(ProgramActivity.java:125) 

maybe your onSuccess() have some issue 
thanks
