### ISSUE TITLE
user-space exception detected

### ISSUE THREAD

**Issue by gillboysimran** [loopj/android-async-http#1125]
I use this Code below 

             AsyncHttpClient client = new AsyncHttpClient();
		               RequestParams params = new RequestParams();
		               params.put("x","testAllOutlet");
		               
	 client.post("http://it.ubislate.com/kaironrestapi/sales_api_test/api_dev-test.php", params, new AsyncHttpResponseHandler() {
		 
			@Override
			public void onFailure(int arg0, Header[] arg1, byte[] arg2,
					Throwable arg3) {
				// TODO Auto-generated method stub
				
			}
			@Override
			public void onSuccess(int arg0, Header[] arg1, byte[] arg2) {
				// TODO Auto-generated method stub
				System.out.println("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"+arg0);
				if (arg0==0) {
					pDialognew.dismiss();
				}

That response getting succesfully but when I save that JSON Array data to  our local sqlitedatabase
database in for loop I getting exception in given below:-

03-03 11:09:55.870: E/AsyncHttpRH(1813): User-space exception detected!
03-03 11:09:55.870: E/AsyncHttpRH(1813): java.lang.NullPointerException
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at com.example.testsqlitedatabase.TestSqlite$1$1.onSuccess(TestSqlite.java:102)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at android.os.Looper.loop(Looper.java:136)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at android.app.ActivityThread.main(ActivityThread.java:5285)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:748)
03-03 11:09:55.870: E/AsyncHttpRH(1813): 	at dalvik.system.NativeStart.main(Native Method)
03-03 11:09:55.870: W/dalvikvm(1813): threadid=1: thread exiting with uncaught exception (group=0x415f9bc0)
03-03 11:09:55.880: E/AndroidRuntime(1813): FATAL EXCEPTION: main
03-03 11:09:55.880: E/AndroidRuntime(1813): Process: com.example.testsqlitedatabase, PID: 1813
03-03 11:09:55.880: E/AndroidRuntime(1813): java.lang.RuntimeException: java.lang.NullPointerException
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at android.os.Looper.loop(Looper.java:136)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at android.app.ActivityThread.main(ActivityThread.java:5285)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:748)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at dalvik.system.NativeStart.main(Native Method)
03-03 11:09:55.880: E/AndroidRuntime(1813): Caused by: java.lang.NullPointerException
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.example.testsqlitedatabase.TestSqlite$1$1.onSuccess(TestSqlite.java:102)
03-03 11:09:55.880: E/AndroidRuntime(1813): 	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)

NOTE:- I Run this Application On the Android Phone.

Please solve this problem or give me any idea of this problem

**Comment by nitinjain90** [comment]
Did you get it solved?

**Comment by elpoisterio** [comment]
I get user exception detected when i try to use toast method in onFailure. Does anyone has a solution for this one.

**Comment by JavadBadirkhanli** [comment]
@elpoisterio don't use Toast method inside onFailure, when app crashed, context is destroying, use Log.
