### ISSUE TITLE
POST request executing with statuscode = 200 but going to onFailure.

### ISSUE THREAD

**Issue by shelarsuhas** [loopj/android-async-http#1129]
I am posting a request to my server and its returning with statusCode = 200 but its going to onFailure.

I tested my code using "https://httpbin.org/post" and its working fine.

But when I request to my server it returns with this exception

```
org.json.JSONException: Response cannot be parsed as JSON data
                                   at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:158)
                                   at android.os.Handler.handleCallback(Handler.java:739)
                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                   at android.os.Looper.loop(Looper.java:148)
                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                   at java.lang.reflect.Method.invoke(Native Method)
                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by benzhadow** [comment]
hello bro, any solution for this case?
 im have same problem

**Comment by guchuanhang** [comment]
Are you free free post your server address ?
