### ISSUE TITLE
JsonHttpResponseHandler failure Exception handling issue

### ISSUE THREAD

**Issue by vinod1988** [loopj/android-async-http#1134]
Hi Team,

I am facing this error. Every time when response not come.. Please handle this on api if response is null then print message instead of exception.

onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
                                                          org.json.JSONException: Response cannot be parsed as JSON data
                                                              at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:158)
                                                              at android.os.Handler.handleCallback(Handler.java:746)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by azizimusa** [comment]
if you trying to print response in onFailure it might have issue. Check for null 1st and if null..just print throwable.toString()

**Comment by kalyanparri** [comment]
Hi Team, I have the same problem
onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
                                                             org.json.JSONException: Response cannot be parsed as JSON data
                                                                 at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:158)
