### ISSUE TITLE
i got this exception but not get the anwser!'java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)'

### ISSUE THREAD

**Issue by parcool** [loopj/android-async-http#1155]
`java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
      at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
      at libcore.io.IoBridge.sendto(IoBridge.java:511)
      at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
      at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
      at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
      at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:114)
      at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:118)
      at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:124)
      at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:94)
      at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:102)
      at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:167)
      at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:277)
      at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:242)
      at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
      at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:444)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
      at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
      at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
      at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)
  Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
      at libcore.io.Posix.sendtoBytes(Native Method)
      at libcore.io.Posix.sendto(Posix.java:211)
      at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
      at libcore.io.IoBridge.sendto(IoBridge.java:509)
    ... 23 more
 3311-3311/com.uiho.deviceinfouploader.proj V/AsyncHttpRH: Request retry no. 1
  java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
      at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
      at libcore.io.IoBridge.sendto(IoBridge.java:511)
      at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
      at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
      at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
      at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:114)
      at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:118)
      at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:124)
      at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:94)
      at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:102)
      at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:167)
      at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:277)
      at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:242)
      at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
      at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:444)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
      at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
      at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
      at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)
  Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
      at libcore.io.Posix.sendtoBytes(Native Method)
      at libcore.io.Posix.sendto(Posix.java:211)
      at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
      at libcore.io.IoBridge.sendto(IoBridge.java:509)`

**Comment by parcool** [comment]
one day past...

**Comment by parcool** [comment]
15 days ago

**Comment by poorna204** [comment]
Did you get any solution? I too have the same issue now.

**Comment by parcool** [comment]
@poorna204 大兄弟，这个库过时了。换其他库吧
