### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by prudhvi948** [loopj/android-async-http#1182]
I'm using this latest version of library in my project and I get a "ConcurrentModificationException".
Exception occurs at line 1578 in this class 
https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java

Here is the stacktrace

1.
java.util.ConcurrentModificationException at java.util.LinkedList$LinkIterator.next(LinkedList.java:124) at com.loopj.android.http.AsyncHttpClient.sendRequest(AsyncHttpClient.java:1526) at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:1169) at com.akamai.android.sdk.internal.e$1.run(Unknown Source) at java.lang.Thread.run(Thread.java:818)

A little bit digging into the issue shows that we have to synchronize the process of iterating the list.

Check out https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList(java.util.List)
http://stackoverflow.com/a/9468307/3701433

**Comment by maxbaldrighi** [comment]
I keep encountering this issue over and over again.
I compile the last stable release (1.4.9) with Gradle.

My stack trace is the same as @prudhvi948 's.

I know from here (https://github.com/loopj/android-async-http/pull/1177/commits/35b68280520cc4df7a1ab8e36009ec8ebb4ab63e) that a pull request was made last summer with a fix but it didn't pass.
