### ISSUE TITLE
VerifyError of sub-classing while new AsyncHttpClient() in Samsung Note3/Android 5.0

### ISSUE THREAD

**Issue by firebear** [loopj/android-async-http#1203]
Not sure if a problem of loopj.android-async-http, I have not been able to find solution in any place. 
You're appreciated for any clue.

> dependencies {
>     compile 'com.android.support:support-v4:24.2.0'
>     compile 'com.loopj.android:android-async-http:1.4.9'
> }
> 

> Android Studio 2.2 Beta 3
> compileSdkVersion 24
> buildToolsVersion '24.0.2'
> minifyEnabled true
> 

the code
> AsyncHttpClient client = new AsyncHttpClient();

Worked fine in many other devices except Samsung Note3/Android 5.0

The exception stacks (minified)
```
09-03 09:41:10.870 E/AndroidRuntime(26563): Process: com.bsx.myapp, PID: 26563
09-03 09:41:10.870 E/AndroidRuntime(26563): java.lang.VerifyError: Rejecting class a.a.a.a.i.b.k that attempts to sub-class erroneous class a.a.a.a.i.b.a (declaration of 'a.a.a.a.i.b.k' appears in /data/app/com.bsx.myapp-1/base.apk)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.loopj.android.http.AsyncHttpClient.<init>(SourceFile:208)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.loopj.android.http.AsyncHttpClient.<init>(SourceFile:177)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.loopj.android.http.AsyncHttpClient.<init>(SourceFile:147)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.bsx.myapp.ad.SplashActivity.c(SourceFile:141)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.bsx.myapp.ad.SplashActivity.onCreate(SourceFile:70)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.Activity.performCreate(Activity.java:6283)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.ActivityThread.access$900(ActivityThread.java:177)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.os.Handler.dispatchMessage(Handler.java:102)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.os.Looper.loop(Looper.java:145)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at android.app.ActivityThread.main(ActivityThread.java:5938)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at java.lang.reflect.Method.invoke(Native Method)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at java.lang.reflect.Method.invoke(Method.java:372)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
09-03 09:41:10.870 E/AndroidRuntime(26563):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-03 09:41:10.870 E/AndroidRuntime(26563): Caused by: java.lang.VerifyError: Rejecting class a.a.a.a.i.b.a because it failed compile-time verification (declaration of 'a.a.a.a.i.b.a' appears in /data/app/com.bsx.myapp-1/base.apk)
09-03 09:41:10.870 E/AndroidRuntime(26563):     ... 18 more
```

**Comment by firebear** [comment]
Finally I figured out it was because of code obfuscating with ProGuard. loopj/async-http-client depends on another 3rd library named cz.msebera.android.httpclient, which should also be kept from bing manified.
