### ISSUE TITLE
Out of memory on file upload.

### ISSUE THREAD

**Issue by mfahy** [loopj/android-async-http#127]
Without fail, any file larger than a couple megs immediately returns an Out-of-Memory error when I attempt to post it using AsyncHTTPRequest. It appears the SimpleMultipartEntity file included builds the file in memory befre sending? Is there a way to get this to chunk & send the file in smaller bites?

```
 FATAL EXCEPTION: main
 java.lang.OutOfMemoryError
 at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
 at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:216)
 at com.loopj.android.http.SimpleMultipartEntity.addPart(SimpleMultipartEntity.java:114)
 at com.loopj.android.http.SimpleMultipartEntity.addPart(SimpleMultipartEntity.java:100)
 at com.loopj.android.http.RequestParams.getEntity(RequestParams.java:234)
 at com.loopj.android.http.AsyncHttpClient.paramsToEntity(AsyncHttpClient.java:584)
 at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:389)
 at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:378)
 at XXX.XXXXXX.XXX.doNet(ZZxxxxClient.java:143)
 at XXX.XXXXXX.XXX.postThread(ZZxxxxClient.java:175)
 at XXX.XXXXXX.X.DelegatedActivity$1.onClick(DelegatedActivity.java:114)
 at android.view.View.performClick(View.java:2537)
 at android.view.View$PerformClick.run(View.java:9157)
 at android.os.Handler.handleCallback(Handler.java:587)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:130)
 at android.app.ActivityThread.main(ActivityThread.java:3687)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:507)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
 at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Queatz** [comment]
Still getting this on 1.4.6.

```
03-25 16:56:22.788  10055-10246/com.everalbum.everalbumapp W/System.err﹕ java.lang.OutOfMemoryError: Failed to allocate a 268429776 byte allocation with 16777120 free bytes and 173MB until OOM
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.SimpleMultipartEntity.addPart(SimpleMultipartEntity.java:139)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.RequestParams.createMultipartEntity(RequestParams.java:515)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.RequestParams.getEntity(RequestParams.java:447)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.AsyncHttpClient.paramsToEntity(AsyncHttpClient.java:1310)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:925)
03-25 16:56:22.789  10055-10246/com.everalbum.everalbumapp W/System.err﹕ at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:912)
```

**Comment by Queatz** [comment]
@smarek this might be because out.flush() is not called until after the whole stream is written to the out object in SimpleMultipartEntity.java:139

**Comment by smarek** [comment]
@Queatz thank you for stacktrace, reopening this and queuing for solving

**Comment by Queatz** [comment]
Awesome

**Comment by smarek** [comment]
Unless we push forward code refactoring, from 1.4.9 you are free to use any MultipartEntity.
With 4.3.3 version of HttpClient included is included whole package of HttpMime of same version, which includes many of these classes. See documentation for reference here: https://hc.apache.org/httpcomponents-client-4.3.x/httpmime/apidocs/index.html

**Comment by 0xAliHn** [comment]
I faced this kind of OOM fatal issues. After investigating 2 days found that the issue is occurring due to use of AsyncHttpClient. Changed AsyncHttpClient to SyncHttpClient and the memory issue goes away.
