### ISSUE TITLE
SSL Socket Read  Time Out

### ISSUE THREAD

**Issue by faizandedia** [loopj/android-async-http#744]
I am trying to post data, always receiving "read Time Out"

Here is the request and respons.

I am using HTTPS URL
applying default security as well:

Please help
```java
MySSLSocketFactory sf = null;
		try {
			KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
			trustStore.load(null, null);
			sf = new MySSLSocketFactory(trustStore);
			sf.setHostnameVerifier(MySSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
			this.setSSLSocketFactory(sf);
		} catch (Exception e) {
		}


String json = copy.asJson();
		
		addHeader("Content-Type", "application/json");
		addHeader("myAuthorization", getAuthHeader());
		
		StringEntity se = null;
		this.setURLEncodingEnabled(false);
        try {
            se = new StringEntity(json);
            se.setContentEncoding(new BasicHeader(HTTP.CONTENT_TYPE, "application/json"));
            se.setChunked(true);


        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
            return;
        }

        setResponseTimeout(10*1000);
		post(ApplicationContext.getContext(), url, se, "application/json", new AsyncHttpResponseHandler() {
			
			@Override
			public void onSuccess(int arg0, Header[] arg1, byte[] arg2) {
				Log.i("", "Success");
				
			}
			
			@Override
			public void onFailure(int arg0, Header[] arg1, byte[] arg2, Throwable arg3) {
				Log.i("", "Failed");
				
			}
		});
```
```
java.net.SocketTimeoutException: Read timed out
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:671)
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)
at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:76)
at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:95)
at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:57)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by xyzgit** [comment]
I run into this problem too

**Comment by babyking** [comment]
same situation.

fix it ,please!

**Comment by inspiredclick** [comment]
Facing this problem as well

**Comment by smarek** [comment]
Can any of you provide backend with which we could debug the issue and fix it? Because on servers I tested with SSL works as supposed. Thank you

**Comment by faizandedia** [comment]
I can not provide it, working for a company.

**Comment by smarek** [comment]
Ok, can you please provide reference environment or test-case using publicly available https server? Not your production environment if you cannot do that.

**Comment by faizandedia** [comment]
I will try to get url for test environment, will email you soon.

**Comment by munnadroid** [comment]
I am also facing this problem, any solution ?

**Comment by amittrantor** [comment]
I am also facing the same issue.

**Comment by gh123man** [comment]
I am facing this issue currently. It is extremely intermittent.
Some important notes:
 This was happening without using the async-http library. However, I was using the async-http persistent cookiestore. When I cleared or disabled the cookiestore, this issue went away. This issue also seems to resolve itself in 1-4 mins, even though it somehow outlives the life-cycle of the application.

**Comment by deathbaba** [comment]
It reproduces on https://www.openstreetmap.org/login

**Comment by makzimi** [comment]
I am also facing this problem. Did anyone solve this? Or may be anyone found what server configuration cause this issue?
Thanks.

**Comment by deepakrathi** [comment]
I am also facing this same issue - any solutions yet ? That too only with jio network operator - anybody got the clue why this is happening? Any solution yet?

**Comment by faizandedia** [comment]
No solution also library is not getting update any more. Better to switch it to some other client. Check retrofit library

**Comment by kbala** [comment]
I am still facing this issue. any solution?

**Comment by deepakrathi** [comment]
Change library, check retrofit or volley for Android

**Comment by chris1206** [comment]
you can add like this,it works for me

AsyncHttpClient client = new AsyncHttpClient();
client.getHttpClient().getParams().setParameter(CoreConnectionPNames.SO_TIMEOUT, 60000); client.getHttpClient().getParams().setParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, 60000);
