### ISSUE TITLE
The target server failed to respond on post with params

### ISSUE THREAD

**Issue by vesy-j** [loopj/android-async-http#774]
Hi I got :
```java
RequestParams params = new RequestParams();
params.put("dish", dishBean.get_id());
params.put("content", dish_comment);
String userName = sp.getString(SharedPreferencesUtil.TAG_USER_NAME, "");
String password = sp.getString(SharedPreferencesUtil.TAG_PASSWORD, "");
String str = userName + ":" + password;
String encodeStr = Base64.encodeToString(str.getBytes(), Base64.DEFAULT);
String loginStr = "Basic " + encodeStr;
NourritureRestClient.addHeader(loginStr);
NourritureRestClient.post("/comments", params, new JsonHttpResponseHandler(
```
If I delete the params and put null, I got the good respond from the server, but with params I got this exception.

I am compile to API lvl 15

stack trace :
```
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ org.apache.http.NoHttpResponseException: The target server failed to respond
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
01-02 15:20:00.947  32289-32305/team_10.nourriture_android W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
01-02 15:20:00.957  32289-32305/team_10.nourriture_android W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
01-02 15:20:00.957  32289-32305/team_10.nourriture_android W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
01-02 15:20:00.957  32289-32305/team_10.nourriture_android W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-02 15:20:00.967  32289-32305/team_10.nourriture_android W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-02 15:20:00.967  32289-32305/team_10.nourriture_android W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-02 15:20:00.967  32289-32305/team_10.nourriture_android W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-02 15:20:00.967  32289-32305/team_10.nourriture_android W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
```

**Comment by vesy-j** [comment]
solved: I should use params.add instead of params.put

**Comment by smarek** [comment]
Well no response from server is probably problem of your backend, not the library. Library doesn't decide whether you'll get response based on what is content of your request, so if you change the params and server responds, it's not problem we could solve for you.

**Comment by vesy-j** [comment]
I test on my side with postman, it works.

But the location of the server is pretty far. I am in china, the server is in France ?

I found the issue I replace the addHeader authentification by using the one of the library:

NourritureRestClient.postWithLogin("comments", params, username, password, new JsonHttpResponseHandler() {

and implemented it like this :

public static void getWithLogin(String url, RequestParams params, String username, String password, AsyncHttpResponseHandler responseHandler) {
        client.setBasicAuth(username, password);
        client.get(getAbsoluteUrl(url), params, responseHandler);
    }

and it works.

https://github.com/vesy-j/Nourriture_Android/blob/master/app/src/main/java/team_10/nourriture_android/activity/DishCommentActivity.java

**Comment by smarek** [comment]
Cool, closing the issue then.
