### ISSUE TITLE
https connection fail: error No peer certificate.

### ISSUE THREAD

**Issue by bj-snowen** [loopj/android-async-http#797]
when i use https connect , there is an error onFailure No peer certificate.
```
01-23 10:04:43.507: W/System.err(17797): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
01-23 10:04:43.522: W/System.err(17797): 	at org.apache.harmony.xnet.provider.jsse.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:137)
01-23 10:04:43.522: W/System.err(17797): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
01-23 10:04:43.522: W/System.err(17797): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:381)
01-23 10:04:43.527: W/System.err(17797): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
01-23 10:04:43.527: W/System.err(17797): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
01-23 10:04:43.527: W/System.err(17797): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
01-23 10:04:43.532: W/System.err(17797): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
01-23 10:04:43.532: W/System.err(17797): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
01-23 10:04:43.532: W/System.err(17797): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
01-23 10:04:43.537: W/System.err(17797): 	at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:148)
01-23 10:04:43.537: W/System.err(17797): 	at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:179)
01-23 10:04:43.537: W/System.err(17797): 	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:108)
01-23 10:04:43.537: W/System.err(17797): 	at com.loopj.android.http.SyncHttpClient.sendRequest(SyncHttpClient.java:95)
01-23 10:04:43.542: W/System.err(17797): 	at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:887)
01-23 10:04:43.542: W/System.err(17797): 	at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:861)
01-23 10:04:43.542: W/System.err(17797): 	at com.yugusoft.fishbone.utils.FBHttpRequest.get(FBHttpRequest.java:35)
01-23 10:04:43.547: W/System.err(17797): 	at com.yugusoft.fishbone.protocol.action.ActUserGet.startAsync(ActUserGet.java:35)
01-23 10:04:43.547: W/System.err(17797): 	at com.yugusoft.fishbone.protocol.ClientHandle.messageReceived(ProtocolUnderLayer.java:391)
01-23 10:04:43.547: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
01-23 10:04:43.552: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
01-23 10:04:43.552: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
01-23 10:04:43.552: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
01-23 10:04:43.557: W/System.err(17797): 	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
01-23 10:04:43.557: W/System.err(17797): 	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
01-23 10:04:43.557: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
01-23 10:04:43.562: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
01-23 10:04:43.562: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
01-23 10:04:43.562: W/System.err(17797): 	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
01-23 10:04:43.567: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
01-23 10:04:43.567: W/System.err(17797): 	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
01-23 10:04:43.567: W/System.err(17797): 	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
01-23 10:04:43.572: W/System.err(17797): 	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
01-23 10:04:43.572: W/System.err(17797): 	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
01-23 10:04:43.572: W/System.err(17797): 	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
01-23 10:04:43.577: W/System.err(17797): 	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
01-23 10:04:43.577: W/System.err(17797): 	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
01-23 10:04:43.577: W/System.err(17797): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
01-23 10:04:43.582: W/System.err(17797): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
01-23 10:04:43.582: W/System.err(17797): 	at java.lang.Thread.run(Thread.java:856)
01-23 10:04:43.592: E/FishBone(17797): [ NioProcessor-9: ActUserGet.java:48 onFailure ] - onFailure No peer certificate
```

**Comment by smarek** [comment]
Well your endpoint certificate isn't trusted in client, either use constructor `AsyncHttpClient(true,80,443)` (will skip ssl certificate trust validation) or use `AsyncHttpClient(SchemeRegistry schemeRegistry)` and provide your own SchemeRegistry with different `SSLSocketFactory` implementation (eg. trust keychain in raw resources of app). See the example of SchemeRegistry init in here: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L188
