### ISSUE TITLE
In WiFi Environment http Request,Loopj sometimes throw org.apache.http.conn.ConnectTimeoutException

### ISSUE THREAD

**Issue by wwwjiandan** [loopj/android-async-http#814]
In WiFi Environment,when invoke Http Request,sometimes appear ConnectTimeoutException,in data NetWork never have this Problem.the loopj version I used is 1.4.4
following is the Exception log:
```
02-26 11:41:15.285: W/System.err(1499): org.apache.http.conn.ConnectTimeoutException: Connect to /117.79.235.226:80 timed out
02-26 11:41:15.289: W/System.err(1499): at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
02-26 11:41:15.289: W/System.err(1499): at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:156)
02-26 11:41:15.289: W/System.err(1499): at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
02-26 11:41:15.292: W/System.err(1499): at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
02-26 11:41:15.292: W/System.err(1499): at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:359)
02-26 11:41:15.296: W/System.err(1499): at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
02-26 11:41:15.296: W/System.err(1499): at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
02-26 11:41:15.300: W/System.err(1499): at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:74)
02-26 11:41:15.300: W/System.err(1499): at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:91)
02-26 11:41:15.300: W/System.err(1499): at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:54)
02-26 11:41:15.300: W/System.err(1499): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
02-26 11:41:15.300: W/System.err(1499): at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
02-26 11:41:15.300: W/System.err(1499): at java.util.concurrent.FutureTask.run(FutureTask.java:138)
02-26 11:41:15.304: W/System.err(1499): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
02-26 11:41:15.304: W/System.err(1499): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
02-26 11:41:15.304: W/System.err(1499): at java.lang.Thread.run(Thread.java:1019)
02-26 11:41:15.308: I/CustomResponseHandler(1499): onFailure Throwable=org.apache.http.conn.ConnectTimeoutException: Connect to /117.79.235.226:80 timed out;ExceptionInfo = null
```

**Comment by smarek** [comment]
@wwwjiandan if you do use version 1.4.4, you're using too old version, test with 1.4.6
we don't support old versions

**Comment by wwwjiandan** [comment]
ok.I know that.

**Comment by wlrnet** [comment]
I also have the same problem, under the environment of WIFI, often send requests directly back to 408.

**Comment by woshixhs** [comment]
I also have the same problem, i use 1.4.6

**Comment by ywtony** [comment]
I also have the same problem. But still will appear this problem.Can you help me ? thanks.

**Comment by pparkppark** [comment]
I also have the same problem, i use 1.4.5

**Comment by smarek** [comment]
Well handle the throwed issue and repeat the request, what is there to be fixed on level of library?
