### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by javagc** [loopj/android-async-http#851]
Hi, I have this code

    AsyncHttpClient sClient = new AsyncHttpClient();
                sClient.setTimeout(20 * 000);
                sClient.setConnectTimeout(20*000);
                sClient.setResponseTimeout(20*000);

                sClient.post("something", requestParams, new      KoalaHttpResponseHandler() {
                    @Override
                    public void onOperationSuccess(String response) {
                        Log.e("d", response);
                    }

                    @Override
                    public void onFailure(String message) {
                        Log.e("de", message);
                    }
                });

and I get the error message in 10 seconds, why 10 seconds?

java.net.SocketTimeoutException: Read timed out
            at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
            at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
            at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
            at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:88)
            at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:179)
            at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:185)
            at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:240)
            at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:264)
            at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:284)
            at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:126)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:433)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
            at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
            at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
            at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by stridera** [comment]
sClient.setTimeout(20 * 000);  You're setting the timeout to 0?

**Comment by javagc** [comment]
Oh no, I am sorry. It was my mistakes, I already fix it, thanks

**Comment by apatil-etouch** [comment]
please let me know how you fixed this.I am getting same error for AsyncHttpClient

**Comment by javagc** [comment]
Hi, it was my mistake sClient.setTimeout(20 * 1000) works for me

**Comment by hardslk** [comment]
sClient.setTimeout(20 * 1000)  it also not work for me

**Comment by javagc** [comment]
please  post your request
