### ISSUE TITLE
anr problem

### ISSUE THREAD

**Issue by wufenglong** [loopj/android-async-http#874]
please help me check the problem, thanks.
```
marksweep + semispace paused:	Sum: 27.694ms 99% C.I. 27.694ms-27.694ms Avg: 27.694ms Max: 27.694ms
marksweep + semispace total time: 27.538ms mean time: 27.538ms
marksweep + semispace freed: 17112 objects with total size 3MB
marksweep + semispace throughput: 633778/s / 125MB/s
Total time spent in GC: 7.385s
Mean GC size throughput: 10MB/s
Mean GC object throughput: 169587 objects/s
Total number of allocations 1324681
Total bytes allocated 83MB
Free memory 749KB
Free memory until GC 749KB
Free memory until OOME 502MB
Total memory 9MB
Max memory 512MB
Total mutator paused time: 109.454ms
Total time waiting for GC to complete: 522.549us

DALVIK THREADS (38):
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74b2bfb8 self=0x55b2afd170
  | sysTid=13404 nice=0 cgrp=default sched=0/0 handle=0x7f7f7240f0
  | state=S schedstat=( 632147750 62103473 1495 ) utm=56 stm=7 core=0 HZ=100
  | stack=0x7feff0a000-0x7feff0c000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x1338e2ce> (a java.lang.String)
  at org.apache.http.impl.conn.tsccm.RefQueueWorker.waitWorkerStart(RefQueueWorker.java:165)
  - locked <0x1338e2ce> (a java.lang.String)
  at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:147)
  at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:120)
  at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:98)
  at com.lenovo.fit.sdk.http.aysnchttp.AsyncHttpClient.createConnectionManager(unavailable:-1)
  at com.lenovo.fit.sdk.http.aysnchttp.AsyncHttpClient.<init>(unavailable:-1)
  at com.lenovo.fit.sdk.http.aysnchttp.AsyncHttpClient.<init>(unavailable:-1)
  at com.lenovo.fit.sdk.http.aysnchttp.AsyncHttpClient.<init>(unavailable:-1)
  at com.lenovo.fit.sdk.AsyncHttpImpl.getInstance(unavailable:-1)
  at com.lenovo.fit.sdk.CloudServiceApi.init(unavailable:-1)
  at com.lenovo.gps.utils.ay.a(unavailable:-1)
```

**Comment by smarek** [comment]
That's indeed problem, however it happens outside of our reach, we're in the stack 5 levels over the lock, does this happen in any specific situation?

Also requests do happen on the background thread, do you have ANR because you're using the SyncHttpClient or because you tie your UI/Main Thread with request progress/finish?

**Comment by MaaTeam** [comment]
I encounter this problem in this situation:
public class MyBroadCastReceiver extends BroadCastReceiver {
public void onReceive(Context context, Intent intent) {
AsyncHttpClient httpClient = new AsyncHttpClient();
httpClient.post(...);
...
}
}
Can you give me some suggust?

**Comment by smarek** [comment]
Not if you won't give us Stacktrace from LogCat or similar debug info.

**Comment by MaaTeam** [comment]
oq: Application Not Responding

Caused by: oq$a$a: main
       at java.lang.Object.wait(Object.java)
       at org.apache.http.impl.conn.tsccm.RefQueueWorker.waitWorkerStart(RefQueueWorker.java:165)
       at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:147)
       at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:120)
       at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.(ThreadSafeClientConnManager.java:98)
       at com.utils.http.a.a()
       at com.nice.main.activities.MainActivity$MainServiceBroadCastReceiver.onReceive(SourceFile:1829)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:912)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5564)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:965)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)

Caused by: oq$a$a: Crashlytics Exception Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(SourceFile:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(SourceFile:30)
       at java.lang.Thread.run(Thread.java:818)
Caused by: oq$a$a: Crashlytics Trace Manager1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1048)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(SourceFile:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(SourceFile:30)
       at java.lang.Thread.run(Thread.java:818)
Caused by: oq$a$a: DNSCache
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:148)
       at android.os.Looper.loop(Looper.java:151)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: oq$a$a: FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:422)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
       at java.lang.Thread.run(Thread.java:818)
Caused by: oq$a$a: FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
       at java.lang.Thread.run(Thread.java:818)
Caused by: oq$a$a: GCDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$GCDaemon.run(Daemons.java:341)
       at java.lang.Thread.run(Thread.java:818)

**Comment by smarek** [comment]
I do not see `loopj` anywhere in the stacktrace, so I assume, it's not problem of this library.

**Comment by MaaTeam** [comment]
The code is confused, i trace problem method below:
    public AsyncHttpClient(SchemeRegistry schemeRegistry) {

        BasicHttpParams httpParams = new BasicHttpParams();

        ConnManagerParams.setTimeout(httpParams, connectTimeout);
        ConnManagerParams.setMaxConnectionsPerRoute(httpParams, new ConnPerRouteBean(maxConnections));
        ConnManagerParams.setMaxTotalConnections(httpParams, DEFAULT_MAX_CONNECTIONS);

        HttpConnectionParams.setSoTimeout(httpParams, responseTimeout);
        HttpConnectionParams.setConnectionTimeout(httpParams, connectTimeout);
        HttpConnectionParams.setTcpNoDelay(httpParams, true);
        HttpConnectionParams.setSocketBufferSize(httpParams, DEFAULT_SOCKET_BUFFER_SIZE);

        HttpProtocolParams.setVersion(httpParams, HttpVersion.HTTP_1_1);

        ThreadSafeClientConnManager cm = new ThreadSafeClientConnManager(httpParams, schemeRegistry);

        threadPool = getDefaultThreadPool();
        requestMap = Collections.synchronizedMap(new WeakHashMap<Context, List<RequestHandle>>());
        clientHeaderMap = new HashMap<String, String>();

        httpContext = new SyncBasicHttpContext(new BasicHttpContext());
        httpClient = new DefaultHttpClient(cm, httpParams);
        httpClient.addRequestInterceptor(new HttpRequestInterceptor() {
            @Override
            public void process(HttpRequest request, HttpContext context) {
                if (!request.containsHeader(HEADER_ACCEPT_ENCODING)) {
                    request.addHeader(HEADER_ACCEPT_ENCODING, ENCODING_GZIP);
                }
                for (String header : clientHeaderMap.keySet()) {
                    if (request.containsHeader(header)) {
                        Header overwritten = request.getFirstHeader(header);
						WspxLog.d(LOG_TAG,
                                String.format("Headers were overwritten! (%s | %s) overwrites (%s | %s)",
                                        header, clientHeaderMap.get(header),
                                        overwritten.getName(), overwritten.getValue())
                        );

                        //remove the overwritten header
                        request.removeHeader(overwritten);
                    }
                    request.addHeader(header, clientHeaderMap.get(header));
                }
            }
        });
here instance ThreadSafeClientConnManager。

**Comment by MaaTeam** [comment]
We found this problem happen on some Android 5.0 phone.

**Comment by konata** [comment]
@MaaTeam @wufenglong any progress on this issue? we stuck in similar  sutiation
