### ISSUE TITLE
Timeouts not catched in onFailure

### ISSUE THREAD

**Issue by nalmada** [loopj/android-async-http#878]
Hi ,

When a org.apache.http.conn.ConnectTimeoutException is thrown , it's never catched by 
```java
onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error)
```

I'm using ```AsyncHttpResponseHandler``` on the version 1.4.7 of the lib.

Here the logcat : 

```java 
06-09 12:31:25.041    6035-6035/com.example.isak.stockumgestionum D/Send RQ POST﹕ https://stock.thedelta.fr/index.php?module=authentication
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ org.apache.http.conn.ConnectTimeoutException: Connect to /37.187.119.11:443 timed out
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:126)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
06-09 12:31:29.056    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:148)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:179)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:108)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-09 12:31:29.057    6035-6281/com.example.isak.stockumgestionum W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
```

Do I do something wrong ? 
How to catch these timeouts ?

Thanks

**Comment by nalmada** [comment]
Seems that was my fault 
Works now
