### ISSUE TITLE
 Does this component support https protocol?

### ISSUE THREAD

**Issue by jeffreylee115** [loopj/android-async-http#972]
I'm working on a android project, and using ca, we need to do https certificate validation between server and app client.  Does this component support https protocol?

**Comment by smarek** [comment]
Hi, you mean client-side pinning and validating chain of trust (hard-coded trust chain or at least CA and maybe intermediate cert) or client-side certificate authorization?

**Comment by LouisLeung** [comment]
same problem. I have set the 

AsyncHttpClient client = new AsyncHttpClient(true,80,443);

10-02 08:24:56.551 5833-5875/com.mgia.androidapp W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9707838: Failure in SSL library, usually a protocol error

10-02 08:24:56.551 5833-5875/com.mgia.androidapp W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9da89901:0x00000000)

.....

10-02 08:24:56.551 5833-5875/com.mgia.androidapp W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9707838: Failure in SSL library, usually a protocol error

10-02 08:24:56.551 5833-5875/com.mgia.androidapp W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9da89901:0x00000000)

**Comment by smarek** [comment]
What version of library do you guys use? SSL support is provided of course. Using `true, 80, 443` constructor, you're overriding SSL validation, which is insecure and will be removed by next release of library probably.

**Comment by FloridaStream** [comment]
same problem with cloudflare, last loopj version(1.4.9).

```

11-25 15:22:35.913 12657-13143/android.my.app W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9680fb8: Failure in SSL library, usually a protocol error
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9dd41d4d:0x00000000)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:436)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.lang.Thread.run(Thread.java:856)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9680fb8: Failure in SSL library, usually a protocol error
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9dd41d4d:0x00000000)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: 	... 20 more
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9680fb8: Failure in SSL library, usually a protocol error
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9dd41d4d:0x00000000)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:436)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at java.lang.Thread.run(Thread.java:856)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9680fb8: Failure in SSL library, usually a protocol error
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x9dd41d4d:0x00000000)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err:     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
11-25 15:22:35.913 12657-13143/android.my.app W/System.err: 	... 20 more

```

running on 

```
public void onLoadResource(WebView view, String s) {...}
```

Please urgent help, i need SSL to protect my app.

@smarek @LouisLeung 
#894

**Comment by Jenuce** [comment]
same program in android 6,  last loopj version(1.4.9)

**Comment by Sumituppal-delhivery** [comment]
Did anyone get the solution?

**Comment by dev01-adroitinfosol** [comment]
Here is the solution for you, This can be applied when you are using server for development purpose.

public SSLContext getSslContext() {

    TrustManager[] byPassTrustManagers = new TrustManager[] { new X509TrustManager() {
        public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
        }

        public void checkClientTrusted(X509Certificate[] chain, String authType) {
        }

        public void checkServerTrusted(X509Certificate[] chain, String authType) {
        }
    } };

    SSLContext sslContext=null;

    try {
        sslContext = SSLContext.getInstance("TLS");
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    try {
        sslContext.init(null, byPassTrustManagers, new SecureRandom());
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }

    return sslContext;

}

 AsyncHttpClient client = new AsyncHttpClient();

 client.setSSLSocketFactory(
            new SSLSocketFactory(getSslContext(),
            SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER));

**Comment by artalgame** [comment]
The same problem for me
