### ISSUE TITLE
cz.msebera.android.httpclient.NoHttpResponseException: The target server failed to respond

### ISSUE THREAD

**Issue by ityancs** [loopj/android-async-http#992]
unfortunatly , i suffered the warning. I try to use `new AsyncHttpClient(true, 0, 0)`,but it doesn't work. I use the version 1.49.

**Comment by jskcse4** [comment]
Me too facing the same problem....
here is the log.

```
10-17 19:12:24.152 27912-28653/com.feez.android W/System.err: cz.msebera.android.httpclient.NoHttpResponseException: The target server failed to respond
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-17 19:12:24.157 27912-28653/com.feez.android W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

**Comment by ityancs** [comment]
I thought is some wrong with the SSL when update, I use UrlConnection to solve the problem.

**Comment by jskcse4** [comment]
Hi @ityancs,
Please show me the sample...

**Comment by jskcse4** [comment]
Fixed this problem by adding the following lines.
```
httpClient.setMaxRetriesAndTimeout(3, 30000);
httpClient.setUserAgent("android-async-http-1.4.9");
```

**Comment by smarek** [comment]
Thanks for solution @jskcse4

**Comment by SpEcHiDe** [comment]
```
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err: cz.msebera.android.httpclient.NoHttpResponseException: shrimadhavuk.me failed to respond
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at me.shrimadhavuk.fortilogin.MainActivity.FortinetActions(MainActivity.java:217)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at me.shrimadhavuk.fortilogin.MainActivity.access$100(MainActivity.java:52)
04-12 21:44:21.031 5424-5615/me.shrimadhavuk.fortilogin W/System.err:     at me.shrimadhavuk.fortilogin.MainActivity$2.run(MainActivity.java:178)
```

error appearing again!!

**Comment by Rameshsam** [comment]
Error apearing again
